# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation  # noqa: E501

    OpenAPI spec version: 1
    Contact: arul@luracast.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.documents_api import DocumentsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDocumentsApi(unittest.TestCase):
    """DocumentsApi unit test stubs"""

    def setUp(self):
        self.api = DocumentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_documents(self):
        """Test case for create_documents

        Upload a file. 🔐  # noqa: E501
        """
        pass

    def test_documents_builddoc(self):
        """Test case for documents_builddoc

        Build a document. 🔐  # noqa: E501
        """
        pass

    def test_documents_retrieve_documents_list_by_element(self):
        """Test case for documents_retrieve_documents_list_by_element

        Return the list of documents of a dedicated element (from its ID or Ref) 🔐  # noqa: E501
        """
        pass

    def test_list_documents(self):
        """Test case for list_documents

        Download a document. 🔐  # noqa: E501
        """
        pass

    def test_remove_documents(self):
        """Test case for remove_documents

        Delete a document. 🔐  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
