# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation  # noqa: E501

    OpenAPI spec version: 1
    Contact: arul@luracast.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.create_shipments_model import CreateShipmentsModel  # noqa: E501
from swagger_client.rest import ApiException


class TestCreateShipmentsModel(unittest.TestCase):
    """CreateShipmentsModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateShipmentsModel(self):
        """Test CreateShipmentsModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.create_shipments_model.CreateShipmentsModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
