# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation  # noqa: E501

    OpenAPI spec version: 1
    Contact: arul@luracast.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.login_api import LoginApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLoginApi(unittest.TestCase):
    """LoginApi unit test stubs"""

    def setUp(self):
        self.api = LoginApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_list_login(self):
        """Test case for list_login

        Login 🔓  # noqa: E501
        """
        pass

    def test_login_login_unsecured(self):
        """Test case for login_login_unsecured

        Login 🔓  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
