# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation  # noqa: E501

    OpenAPI spec version: 1
    Contact: arul@luracast.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.supplierinvoices_api import SupplierinvoicesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSupplierinvoicesApi(unittest.TestCase):
    """SupplierinvoicesApi unit test stubs"""

    def setUp(self):
        self.api = SupplierinvoicesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_supplierinvoices(self):
        """Test case for create_supplierinvoices

        Create supplier invoice object 🔐  # noqa: E501
        """
        pass

    def test_list_supplierinvoices(self):
        """Test case for list_supplierinvoices

        List invoices 🔐  # noqa: E501
        """
        pass

    def test_remove_supplierinvoices(self):
        """Test case for remove_supplierinvoices

        Delete supplier invoice 🔐  # noqa: E501
        """
        pass

    def test_retrieve_supplierinvoices(self):
        """Test case for retrieve_supplierinvoices

        Get properties of a supplier invoice object 🔐  # noqa: E501
        """
        pass

    def test_supplierinvoices_add_payment(self):
        """Test case for supplierinvoices_add_payment

        Add payment line to a specific supplier invoice with the remain to pay as amount. 🔐  # noqa: E501
        """
        pass

    def test_supplierinvoices_create_line(self):
        """Test case for supplierinvoices_create_line

        Add a line to given supplier invoice 🔐  # noqa: E501
        """
        pass

    def test_supplierinvoices_remove_line(self):
        """Test case for supplierinvoices_remove_line

        Deletes a line of a given supplier invoice 🔐  # noqa: E501
        """
        pass

    def test_supplierinvoices_retrieve_lines(self):
        """Test case for supplierinvoices_retrieve_lines

        Get lines of a supplier invoice 🔐  # noqa: E501
        """
        pass

    def test_supplierinvoices_retrieve_payments(self):
        """Test case for supplierinvoices_retrieve_payments

        Get list of payments of a given supplier invoice 🔐  # noqa: E501
        """
        pass

    def test_supplierinvoices_update_line(self):
        """Test case for supplierinvoices_update_line

        Update a line to a given supplier invoice 🔐  # noqa: E501
        """
        pass

    def test_supplierinvoices_validate(self):
        """Test case for supplierinvoices_validate

        Validate an invoice 🔐  # noqa: E501
        """
        pass

    def test_update_supplierinvoices(self):
        """Test case for update_supplierinvoices

        Update supplier invoice 🔐  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
