# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation  # noqa: E501

    OpenAPI spec version: 1
    Contact: arul@luracast.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.update_contacts_model import UpdateContactsModel  # noqa: E501
from swagger_client.rest import ApiException


class TestUpdateContactsModel(unittest.TestCase):
    """UpdateContactsModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateContactsModel(self):
        """Test UpdateContactsModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.update_contacts_model.UpdateContactsModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
