# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation  # noqa: E501

    OpenAPI spec version: 1
    Contact: arul@luracast.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.contacts_api import ContactsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestContactsApi(unittest.TestCase):
    """ContactsApi unit test stubs"""

    def setUp(self):
        self.api = ContactsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_contacts_add_category(self):
        """Test case for contacts_add_category

        Add a category to a contact 🔐  # noqa: E501
        """
        pass

    def test_contacts_create_user(self):
        """Test case for contacts_create_user

        Create an user account object from contact (external user) 🔐  # noqa: E501
        """
        pass

    def test_contacts_remove_category(self):
        """Test case for contacts_remove_category

        Remove the link between a category and a contact 🔐  # noqa: E501
        """
        pass

    def test_contacts_retrieve_by_email(self):
        """Test case for contacts_retrieve_by_email

        Get properties of a contact object by Email 🔐  # noqa: E501
        """
        pass

    def test_contacts_retrieve_categories(self):
        """Test case for contacts_retrieve_categories

        Get categories for a contact 🔐  # noqa: E501
        """
        pass

    def test_create_contacts(self):
        """Test case for create_contacts

        Create contact object 🔐  # noqa: E501
        """
        pass

    def test_list_contacts(self):
        """Test case for list_contacts

        List contacts 🔐  # noqa: E501
        """
        pass

    def test_remove_contacts(self):
        """Test case for remove_contacts

        Delete contact 🔐  # noqa: E501
        """
        pass

    def test_retrieve_contacts(self):
        """Test case for retrieve_contacts

        Get properties of a contact object 🔐  # noqa: E501
        """
        pass

    def test_update_contacts(self):
        """Test case for update_contacts

        Update contact 🔐  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
