# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation  # noqa: E501

    OpenAPI spec version: 1
    Contact: arul@luracast.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.shipments_api import ShipmentsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestShipmentsApi(unittest.TestCase):
    """ShipmentsApi unit test stubs"""

    def setUp(self):
        self.api = ShipmentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_shipments(self):
        """Test case for create_shipments

        Create shipment object 🔐  # noqa: E501
        """
        pass

    def test_list_shipments(self):
        """Test case for list_shipments

        List shipments 🔐  # noqa: E501
        """
        pass

    def test_remove_shipments(self):
        """Test case for remove_shipments

        Delete shipment 🔐  # noqa: E501
        """
        pass

    def test_retrieve_shipments(self):
        """Test case for retrieve_shipments

        Get properties of a shipment object 🔐  # noqa: E501
        """
        pass

    def test_shipments_remove_line(self):
        """Test case for shipments_remove_line

        Delete a line to given shipment 🔐  # noqa: E501
        """
        pass

    def test_shipments_validate(self):
        """Test case for shipments_validate

        Validate a shipment 🔐  # noqa: E501
        """
        pass

    def test_update_shipments(self):
        """Test case for update_shipments

        Update shipment general fields (won't touch lines of shipment) 🔐  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
