# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation  # noqa: E501

    OpenAPI spec version: 1
    Contact: arul@luracast.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.create_proposals_model import CreateProposalsModel  # noqa: E501
from swagger_client.rest import ApiException


class TestCreateProposalsModel(unittest.TestCase):
    """CreateProposalsModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateProposalsModel(self):
        """Test CreateProposalsModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.create_proposals_model.CreateProposalsModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
