# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation  # noqa: E501

    OpenAPI spec version: 1
    Contact: arul@luracast.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.update_supplierorders_model import UpdateSupplierordersModel  # noqa: E501
from swagger_client.rest import ApiException


class TestUpdateSupplierordersModel(unittest.TestCase):
    """UpdateSupplierordersModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateSupplierordersModel(self):
        """Test UpdateSupplierordersModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.update_supplierorders_model.UpdateSupplierordersModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
