# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation  # noqa: E501

    OpenAPI spec version: 1
    Contact: arul@luracast.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.products_add_attribute_value_model import ProductsAddAttributeValueModel  # noqa: E501
from swagger_client.rest import ApiException


class TestProductsAddAttributeValueModel(unittest.TestCase):
    """ProductsAddAttributeValueModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProductsAddAttributeValueModel(self):
        """Test ProductsAddAttributeValueModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.products_add_attribute_value_model.ProductsAddAttributeValueModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
