# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation  # noqa: E501

    OpenAPI spec version: 1
    Contact: arul@luracast.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.tickets_api import TicketsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTicketsApi(unittest.TestCase):
    """TicketsApi unit test stubs"""

    def setUp(self):
        self.api = TicketsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_tickets(self):
        """Test case for create_tickets

        Create ticket object 🔐  # noqa: E501
        """
        pass

    def test_list_tickets(self):
        """Test case for list_tickets

        List tickets 🔐  # noqa: E501
        """
        pass

    def test_remove_tickets(self):
        """Test case for remove_tickets

        Delete ticket 🔐  # noqa: E501
        """
        pass

    def test_retrieve_tickets(self):
        """Test case for retrieve_tickets

        Get properties of a Ticket object. 🔐  # noqa: E501
        """
        pass

    def test_tickets_create_new_message(self):
        """Test case for tickets_create_new_message

        Create ticket object 🔐  # noqa: E501
        """
        pass

    def test_tickets_retrieve_by_ref(self):
        """Test case for tickets_retrieve_by_ref

        Get properties of a Ticket object from ref 🔐  # noqa: E501
        """
        pass

    def test_tickets_retrieve_by_track_id(self):
        """Test case for tickets_retrieve_by_track_id

        Get properties of a Ticket object from track id 🔐  # noqa: E501
        """
        pass

    def test_update_tickets(self):
        """Test case for update_tickets

        Update ticket 🔐  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
