# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation  # noqa: E501

    OpenAPI spec version: 1
    Contact: arul@luracast.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.thirdparties_modify_societe_account_model import ThirdpartiesModifySocieteAccountModel  # noqa: E501
from swagger_client.rest import ApiException


class TestThirdpartiesModifySocieteAccountModel(unittest.TestCase):
    """ThirdpartiesModifySocieteAccountModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testThirdpartiesModifySocieteAccountModel(self):
        """Test ThirdpartiesModifySocieteAccountModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.thirdparties_modify_societe_account_model.ThirdpartiesModifySocieteAccountModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
