# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation  # noqa: E501

    OpenAPI spec version: 1
    Contact: arul@luracast.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.supplierinvoices_add_payment_model import SupplierinvoicesAddPaymentModel  # noqa: E501
from swagger_client.rest import ApiException


class TestSupplierinvoicesAddPaymentModel(unittest.TestCase):
    """SupplierinvoicesAddPaymentModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSupplierinvoicesAddPaymentModel(self):
        """Test SupplierinvoicesAddPaymentModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.supplierinvoices_add_payment_model.SupplierinvoicesAddPaymentModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
