# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation  # noqa: E501

    OpenAPI spec version: 1
    Contact: arul@luracast.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.warehouses_api import WarehousesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestWarehousesApi(unittest.TestCase):
    """WarehousesApi unit test stubs"""

    def setUp(self):
        self.api = WarehousesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_warehouses(self):
        """Test case for create_warehouses

        Create warehouse object 🔐  # noqa: E501
        """
        pass

    def test_list_warehouses(self):
        """Test case for list_warehouses

        List warehouses 🔐  # noqa: E501
        """
        pass

    def test_remove_warehouses(self):
        """Test case for remove_warehouses

        Delete warehouse 🔐  # noqa: E501
        """
        pass

    def test_retrieve_warehouses(self):
        """Test case for retrieve_warehouses

        Get properties of a warehouse object 🔐  # noqa: E501
        """
        pass

    def test_update_warehouses(self):
        """Test case for update_warehouses

        Update warehouse 🔐  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
