# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation  # noqa: E501

    OpenAPI spec version: 1
    Contact: arul@luracast.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.stockmovements_api import StockmovementsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestStockmovementsApi(unittest.TestCase):
    """StockmovementsApi unit test stubs"""

    def setUp(self):
        self.api = StockmovementsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_stockmovements(self):
        """Test case for create_stockmovements

        Create stock movement object. 🔐  # noqa: E501
        """
        pass

    def test_list_stockmovements(self):
        """Test case for list_stockmovements

        Get a list of stock movement 🔐  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
