# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation  # noqa: E501

    OpenAPI spec version: 1
    Contact: arul@luracast.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.products_api import ProductsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProductsApi(unittest.TestCase):
    """ProductsApi unit test stubs"""

    def setUp(self):
        self.api = ProductsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_products(self):
        """Test case for create_products

        Create product object 🔐  # noqa: E501
        """
        pass

    def test_list_products(self):
        """Test case for list_products

        List products 🔐  # noqa: E501
        """
        pass

    def test_products_add_attribute_value(self):
        """Test case for products_add_attribute_value

        Add attribute value. 🔐  # noqa: E501
        """
        pass

    def test_products_add_attributes(self):
        """Test case for products_add_attributes

        Add attributes. 🔐  # noqa: E501
        """
        pass

    def test_products_add_purchase_price(self):
        """Test case for products_add_purchase_price

        Add/Update purchase prices for a product. 🔐  # noqa: E501
        """
        pass

    def test_products_add_subproducts(self):
        """Test case for products_add_subproducts

        Add subproduct. 🔐  # noqa: E501
        """
        pass

    def test_products_add_variant(self):
        """Test case for products_add_variant

        Add variant. 🔐  # noqa: E501
        """
        pass

    def test_products_add_variant_by_product_ref(self):
        """Test case for products_add_variant_by_product_ref

        Add variant by product ref. 🔐  # noqa: E501
        """
        pass

    def test_products_del_subproducts(self):
        """Test case for products_del_subproducts

        Remove subproduct. 🔐  # noqa: E501
        """
        pass

    def test_products_remove_attribute_value_by_id(self):
        """Test case for products_remove_attribute_value_by_id

        Delete attribute value by id. 🔐  # noqa: E501
        """
        pass

    def test_products_remove_attribute_value_by_ref(self):
        """Test case for products_remove_attribute_value_by_ref

        Delete attribute value by ref. 🔐  # noqa: E501
        """
        pass

    def test_products_remove_attributes(self):
        """Test case for products_remove_attributes

        Delete attributes by id. 🔐  # noqa: E501
        """
        pass

    def test_products_remove_purchase_price(self):
        """Test case for products_remove_purchase_price

        Delete purchase price for a product 🔐  # noqa: E501
        """
        pass

    def test_products_remove_variant(self):
        """Test case for products_remove_variant

        Delete product variants. 🔐  # noqa: E501
        """
        pass

    def test_products_retrieve_attribute_by_id(self):
        """Test case for products_retrieve_attribute_by_id

        Get attribute by ID. 🔐  # noqa: E501
        """
        pass

    def test_products_retrieve_attribute_value_by_id(self):
        """Test case for products_retrieve_attribute_value_by_id

        Get attribute value by id. 🔐  # noqa: E501
        """
        pass

    def test_products_retrieve_attribute_value_by_ref(self):
        """Test case for products_retrieve_attribute_value_by_ref

        Get attribute value by ref. 🔐  # noqa: E501
        """
        pass

    def test_products_retrieve_attribute_values(self):
        """Test case for products_retrieve_attribute_values

        Get all values for an attribute id. 🔐  # noqa: E501
        """
        pass

    def test_products_retrieve_attribute_values_by_ref(self):
        """Test case for products_retrieve_attribute_values_by_ref

        Get all values for an attribute ref. 🔐  # noqa: E501
        """
        pass

    def test_products_retrieve_attributes(self):
        """Test case for products_retrieve_attributes

        Get attributes. 🔐  # noqa: E501
        """
        pass

    def test_products_retrieve_attributes_by_ref(self):
        """Test case for products_retrieve_attributes_by_ref

        Get attributes by ref. 🔐  # noqa: E501
        """
        pass

    def test_products_retrieve_attributes_by_ref_ext(self):
        """Test case for products_retrieve_attributes_by_ref_ext

        Get attributes by ref_ext. 🔐  # noqa: E501
        """
        pass

    def test_products_retrieve_by_barcode(self):
        """Test case for products_retrieve_by_barcode

        Get properties of a product object by barcode 🔐  # noqa: E501
        """
        pass

    def test_products_retrieve_by_ref(self):
        """Test case for products_retrieve_by_ref

        Get properties of a product object by ref 🔐  # noqa: E501
        """
        pass

    def test_products_retrieve_by_ref_ext(self):
        """Test case for products_retrieve_by_ref_ext

        Get properties of a product object by ref_ext 🔐  # noqa: E501
        """
        pass

    def test_products_retrieve_categories(self):
        """Test case for products_retrieve_categories

        Get categories for a product 🔐  # noqa: E501
        """
        pass

    def test_products_retrieve_customer_prices_per_customer(self):
        """Test case for products_retrieve_customer_prices_per_customer

        Get prices per customer for a product 🔐  # noqa: E501
        """
        pass

    def test_products_retrieve_customer_prices_per_quantity(self):
        """Test case for products_retrieve_customer_prices_per_quantity

        Get prices per quantity for a product 🔐  # noqa: E501
        """
        pass

    def test_products_retrieve_customer_prices_per_segment(self):
        """Test case for products_retrieve_customer_prices_per_segment

        Get prices per segment for a product 🔐  # noqa: E501
        """
        pass

    def test_products_retrieve_purchase_prices(self):
        """Test case for products_retrieve_purchase_prices

        Get purchase prices for a product 🔐  # noqa: E501
        """
        pass

    def test_products_retrieve_stock(self):
        """Test case for products_retrieve_stock

        Get stock data for the product id given. 🔐  # noqa: E501
        """
        pass

    def test_products_retrieve_subproducts(self):
        """Test case for products_retrieve_subproducts

        Get the list of subproducts of the product. 🔐  # noqa: E501
        """
        pass

    def test_products_retrieve_supplier_products(self):
        """Test case for products_retrieve_supplier_products

        Get a list of all purchase prices of products 🔐  # noqa: E501
        """
        pass

    def test_products_retrieve_variants(self):
        """Test case for products_retrieve_variants

        Get product variants. 🔐  # noqa: E501
        """
        pass

    def test_products_retrieve_variants_by_prod_ref(self):
        """Test case for products_retrieve_variants_by_prod_ref

        Get product variants by Product ref. 🔐  # noqa: E501
        """
        pass

    def test_products_update_attribute_value(self):
        """Test case for products_update_attribute_value

        Update attribute value. 🔐  # noqa: E501
        """
        pass

    def test_products_update_attributes(self):
        """Test case for products_update_attributes

        Update attributes by id. 🔐  # noqa: E501
        """
        pass

    def test_products_update_variant(self):
        """Test case for products_update_variant

        Put product variants. 🔐  # noqa: E501
        """
        pass

    def test_remove_products(self):
        """Test case for remove_products

        Delete product 🔐  # noqa: E501
        """
        pass

    def test_retrieve_products(self):
        """Test case for retrieve_products

        Get properties of a product object by id 🔐  # noqa: E501
        """
        pass

    def test_update_products(self):
        """Test case for update_products

        Update product. 🔐  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
