# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation  # noqa: E501

    OpenAPI spec version: 1
    Contact: arul@luracast.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.invoices_add_contact_model import InvoicesAddContactModel  # noqa: E501
from swagger_client.rest import ApiException


class TestInvoicesAddContactModel(unittest.TestCase):
    """InvoicesAddContactModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInvoicesAddContactModel(self):
        """Test InvoicesAddContactModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.invoices_add_contact_model.InvoicesAddContactModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
