# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation  # noqa: E501

    OpenAPI spec version: 1
    Contact: arul@luracast.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.bankaccounts_add_line_model import BankaccountsAddLineModel  # noqa: E501
from swagger_client.rest import ApiException


class TestBankaccountsAddLineModel(unittest.TestCase):
    """BankaccountsAddLineModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBankaccountsAddLineModel(self):
        """Test BankaccountsAddLineModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.bankaccounts_add_line_model.BankaccountsAddLineModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
