# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation  # noqa: E501

    OpenAPI spec version: 1
    Contact: arul@luracast.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.thirdparties_api import ThirdpartiesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestThirdpartiesApi(unittest.TestCase):
    """ThirdpartiesApi unit test stubs"""

    def setUp(self):
        self.api = ThirdpartiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_thirdparties(self):
        """Test case for create_thirdparties

        Create thirdparty object 🔐  # noqa: E501
        """
        pass

    def test_list_thirdparties(self):
        """Test case for list_thirdparties

        List thirdparties 🔐  # noqa: E501
        """
        pass

    def test_remove_thirdparties(self):
        """Test case for remove_thirdparties

        Delete thirdparty 🔐  # noqa: E501
        """
        pass

    def test_retrieve_thirdparties(self):
        """Test case for retrieve_thirdparties

        Get properties of a thirdparty object 🔐  # noqa: E501
        """
        pass

    def test_thirdparties_add_category(self):
        """Test case for thirdparties_add_category

        Add a customer category to a thirdparty 🔐  # noqa: E501
        """
        pass

    def test_thirdparties_add_supplier_category(self):
        """Test case for thirdparties_add_supplier_category

        Add a supplier category to a thirdparty 🔐  # noqa: E501
        """
        pass

    def test_thirdparties_create_company_bank_account(self):
        """Test case for thirdparties_create_company_bank_account

        Create CompanyBankAccount object for thirdparty 🔐  # noqa: E501
        """
        pass

    def test_thirdparties_create_societe_account(self):
        """Test case for thirdparties_create_societe_account

        Create and attach a new gateway to an existing thirdparty 🔐  # noqa: E501
        """
        pass

    def test_thirdparties_generate_bank_account_document(self):
        """Test case for thirdparties_generate_bank_account_document

        Generate a Document from a bank account record (like SEPA mandate) 🔐  # noqa: E501
        """
        pass

    def test_thirdparties_merge(self):
        """Test case for thirdparties_merge

        Merge a thirdparty into another one. 🔐  # noqa: E501
        """
        pass

    def test_thirdparties_modify_societe_account(self):
        """Test case for thirdparties_modify_societe_account

        Update specified values of a specific gateway attached to a thirdparty 🔐  # noqa: E501
        """
        pass

    def test_thirdparties_remove_category(self):
        """Test case for thirdparties_remove_category

        Remove the link between a customer category and the thirdparty 🔐  # noqa: E501
        """
        pass

    def test_thirdparties_remove_company_bank_account(self):
        """Test case for thirdparties_remove_company_bank_account

        Delete a bank account attached to a thirdparty 🔐  # noqa: E501
        """
        pass

    def test_thirdparties_remove_societe_account(self):
        """Test case for thirdparties_remove_societe_account

        Delete a specific site gateway attached to a thirdparty (by gateway id) 🔐  # noqa: E501
        """
        pass

    def test_thirdparties_remove_societe_accounts(self):
        """Test case for thirdparties_remove_societe_accounts

        Delete all gateways attached to a thirdparty 🔐  # noqa: E501
        """
        pass

    def test_thirdparties_remove_supplier_category(self):
        """Test case for thirdparties_remove_supplier_category

        Remove the link between a category and the thirdparty 🔐  # noqa: E501
        """
        pass

    def test_thirdparties_retrieve_by_barcode(self):
        """Test case for thirdparties_retrieve_by_barcode

        Get properties of a thirdparty object by barcode. 🔐  # noqa: E501
        """
        pass

    def test_thirdparties_retrieve_by_email(self):
        """Test case for thirdparties_retrieve_by_email

        Get properties of a thirdparty object by email. 🔐  # noqa: E501
        """
        pass

    def test_thirdparties_retrieve_categories(self):
        """Test case for thirdparties_retrieve_categories

        Get customer categories for a thirdparty 🔐  # noqa: E501
        """
        pass

    def test_thirdparties_retrieve_company_bank_account(self):
        """Test case for thirdparties_retrieve_company_bank_account

        Get CompanyBankAccount objects for thirdparty 🔐  # noqa: E501
        """
        pass

    def test_thirdparties_retrieve_fixed_amount_discounts(self):
        """Test case for thirdparties_retrieve_fixed_amount_discounts

        Get fixed amount discount of a thirdparty (all sources: deposit, credit note, commercial offers...) 🔐  # noqa: E501
        """
        pass

    def test_thirdparties_retrieve_invoices_qualified_for_credit_note(self):
        """Test case for thirdparties_retrieve_invoices_qualified_for_credit_note

        Return list of invoices qualified to be corrected by a credit note. 🔐  # noqa: E501
        """
        pass

    def test_thirdparties_retrieve_invoices_qualified_for_replacement(self):
        """Test case for thirdparties_retrieve_invoices_qualified_for_replacement

        Return list of invoices qualified to be replaced by another invoice. 🔐  # noqa: E501
        """
        pass

    def test_thirdparties_retrieve_out_standing_invoices(self):
        """Test case for thirdparties_retrieve_out_standing_invoices

        Get outstanding invoices of thirdparty 🔐  # noqa: E501
        """
        pass

    def test_thirdparties_retrieve_out_standing_order(self):
        """Test case for thirdparties_retrieve_out_standing_order

        Get outstanding orders of thirdparty 🔐  # noqa: E501
        """
        pass

    def test_thirdparties_retrieve_out_standing_proposals(self):
        """Test case for thirdparties_retrieve_out_standing_proposals

        Get outstanding proposals of thirdparty 🔐  # noqa: E501
        """
        pass

    def test_thirdparties_retrieve_sales_representatives(self):
        """Test case for thirdparties_retrieve_sales_representatives

        Get representatives of thirdparty 🔐  # noqa: E501
        """
        pass

    def test_thirdparties_retrieve_societe_accounts(self):
        """Test case for thirdparties_retrieve_societe_accounts

        Get a specific gateway attached to a thirdparty (by specifying the site key) 🔐  # noqa: E501
        """
        pass

    def test_thirdparties_retrieve_supplier_categories(self):
        """Test case for thirdparties_retrieve_supplier_categories

        Get supplier categories for a thirdparty 🔐  # noqa: E501
        """
        pass

    def test_thirdparties_set_thirdparty_price_level(self):
        """Test case for thirdparties_set_thirdparty_price_level

        Set new price level for the given thirdparty 🔐  # noqa: E501
        """
        pass

    def test_thirdparties_update_company_bank_account(self):
        """Test case for thirdparties_update_company_bank_account

        Update CompanyBankAccount object for thirdparty 🔐  # noqa: E501
        """
        pass

    def test_thirdparties_update_societe_account(self):
        """Test case for thirdparties_update_societe_account

        Create and attach a new (or replace an existing) specific site gateway to a thirdparty 🔐  # noqa: E501
        """
        pass

    def test_update_thirdparties(self):
        """Test case for update_thirdparties

        Update thirdparty 🔐  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
