# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation  # noqa: E501

    OpenAPI spec version: 1
    Contact: arul@luracast.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.invoices_api import InvoicesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestInvoicesApi(unittest.TestCase):
    """InvoicesApi unit test stubs"""

    def setUp(self):
        self.api = InvoicesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_invoices(self):
        """Test case for create_invoices

        Create invoice object 🔐  # noqa: E501
        """
        pass

    def test_invoices_add_contact(self):
        """Test case for invoices_add_contact

        Adds a contact to an invoice 🔐  # noqa: E501
        """
        pass

    def test_invoices_add_payment(self):
        """Test case for invoices_add_payment

        Add payment line to a specific invoice with the remain to pay as amount. 🔐  # noqa: E501
        """
        pass

    def test_invoices_add_payment_distributed(self):
        """Test case for invoices_add_payment_distributed

        Add a payment to pay partially or completely one or several invoices. 🔐  # noqa: E501
        """
        pass

    def test_invoices_create_contact(self):
        """Test case for invoices_create_contact

        Add a contact type of given invoice 🔐  # noqa: E501
        """
        pass

    def test_invoices_create_invoice_from_order(self):
        """Test case for invoices_create_invoice_from_order

        Create an invoice using an existing order. 🔐  # noqa: E501
        """
        pass

    def test_invoices_create_line(self):
        """Test case for invoices_create_line

        Add a line to a given invoice 🔐  # noqa: E501
        """
        pass

    def test_invoices_mark_as_credit_available(self):
        """Test case for invoices_mark_as_credit_available

        Create a discount (credit available) for a credit note or a deposit. 🔐  # noqa: E501
        """
        pass

    def test_invoices_remove_contact(self):
        """Test case for invoices_remove_contact

        Delete a contact type of given invoice 🔐  # noqa: E501
        """
        pass

    def test_invoices_remove_line(self):
        """Test case for invoices_remove_line

        Deletes a line of a given invoice 🔐  # noqa: E501
        """
        pass

    def test_invoices_retrieve_by_ref(self):
        """Test case for invoices_retrieve_by_ref

        Get properties of an invoice object by ref 🔐  # noqa: E501
        """
        pass

    def test_invoices_retrieve_by_ref_ext(self):
        """Test case for invoices_retrieve_by_ref_ext

        Get properties of an invoice object by ref_ext 🔐  # noqa: E501
        """
        pass

    def test_invoices_retrieve_discount(self):
        """Test case for invoices_retrieve_discount

        Get discount from invoice 🔐  # noqa: E501
        """
        pass

    def test_invoices_retrieve_lines(self):
        """Test case for invoices_retrieve_lines

        Get lines of an invoice 🔐  # noqa: E501
        """
        pass

    def test_invoices_retrieve_payments(self):
        """Test case for invoices_retrieve_payments

        Get list of payments of a given invoice 🔐  # noqa: E501
        """
        pass

    def test_invoices_settodraft(self):
        """Test case for invoices_settodraft

        Sets an invoice as draft 🔐  # noqa: E501
        """
        pass

    def test_invoices_settopaid(self):
        """Test case for invoices_settopaid

        Sets an invoice as paid 🔐  # noqa: E501
        """
        pass

    def test_invoices_settounpaid(self):
        """Test case for invoices_settounpaid

        Sets an invoice as unpaid 🔐  # noqa: E501
        """
        pass

    def test_invoices_update_line(self):
        """Test case for invoices_update_line

        Update a line to a given invoice 🔐  # noqa: E501
        """
        pass

    def test_invoices_update_payment(self):
        """Test case for invoices_update_payment

        Update a payment 🔐  # noqa: E501
        """
        pass

    def test_invoices_use_credit_note(self):
        """Test case for invoices_use_credit_note

        Add an available credit note discount to payments of an existing invoice. 🔐  # noqa: E501
        """
        pass

    def test_invoices_use_discount(self):
        """Test case for invoices_use_discount

        Add a discount line into an invoice (as an invoice line) using an existing absolute discount 🔐  # noqa: E501
        """
        pass

    def test_invoices_validate(self):
        """Test case for invoices_validate

        Validate an invoice 🔐  # noqa: E501
        """
        pass

    def test_list_invoices(self):
        """Test case for list_invoices

        List invoices 🔐  # noqa: E501
        """
        pass

    def test_remove_invoices(self):
        """Test case for remove_invoices

        Delete invoice 🔐  # noqa: E501
        """
        pass

    def test_retrieve_invoices(self):
        """Test case for retrieve_invoices

        Get properties of a invoice object 🔐  # noqa: E501
        """
        pass

    def test_update_invoices(self):
        """Test case for update_invoices

        Update invoice 🔐  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
