# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation  # noqa: E501

    OpenAPI spec version: 1
    Contact: arul@luracast.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.invoices_validate_model import InvoicesValidateModel  # noqa: E501
from swagger_client.rest import ApiException


class TestInvoicesValidateModel(unittest.TestCase):
    """InvoicesValidateModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInvoicesValidateModel(self):
        """Test InvoicesValidateModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.invoices_validate_model.InvoicesValidateModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
