# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation  # noqa: E501

    OpenAPI spec version: 1
    Contact: arul@luracast.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.setup_api import SetupApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSetupApi(unittest.TestCase):
    """SetupApi unit test stubs"""

    def setUp(self):
        self.api = SetupApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_setup_retrieve_availability(self):
        """Test case for setup_retrieve_availability

        Get the list of delivery times. 🔐  # noqa: E501
        """
        pass

    def test_setup_retrieve_check_integrity(self):
        """Test case for setup_retrieve_check_integrity

        Do a test of integrity for files and setup. 🔐  # noqa: E501
        """
        pass

    def test_setup_retrieve_company(self):
        """Test case for setup_retrieve_company

        Get properties of company 🔐  # noqa: E501
        """
        pass

    def test_setup_retrieve_conf(self):
        """Test case for setup_retrieve_conf

        Get value of a setup variables 🔐  # noqa: E501
        """
        pass

    def test_setup_retrieve_country_by_code(self):
        """Test case for setup_retrieve_country_by_code

        Get country by Code. 🔐  # noqa: E501
        """
        pass

    def test_setup_retrieve_country_by_id(self):
        """Test case for setup_retrieve_country_by_id

        Get country by ID. 🔐  # noqa: E501
        """
        pass

    def test_setup_retrieve_country_by_iso(self):
        """Test case for setup_retrieve_country_by_iso

        Get country by Iso. 🔐  # noqa: E501
        """
        pass

    def test_setup_retrieve_list_of_civilities(self):
        """Test case for setup_retrieve_list_of_civilities

        Get the list of civilities. 🔐  # noqa: E501
        """
        pass

    def test_setup_retrieve_list_of_contact_types(self):
        """Test case for setup_retrieve_list_of_contact_types

        Get the list of contacts types. 🔐  # noqa: E501
        """
        pass

    def test_setup_retrieve_list_of_countries(self):
        """Test case for setup_retrieve_list_of_countries

        Get the list of countries. 🔐  # noqa: E501
        """
        pass

    def test_setup_retrieve_list_of_currencies(self):
        """Test case for setup_retrieve_list_of_currencies

        Get the list of currencies. 🔐  # noqa: E501
        """
        pass

    def test_setup_retrieve_list_of_event_types(self):
        """Test case for setup_retrieve_list_of_event_types

        Get the list of events types. 🔐  # noqa: E501
        """
        pass

    def test_setup_retrieve_list_of_expense_reports_types(self):
        """Test case for setup_retrieve_list_of_expense_reports_types

        Get the list of Expense Report types. 🔐  # noqa: E501
        """
        pass

    def test_setup_retrieve_list_of_extrafields(self):
        """Test case for setup_retrieve_list_of_extrafields

        Get the list of extra fields. 🔐  # noqa: E501
        """
        pass

    def test_setup_retrieve_list_of_measuring_units(self):
        """Test case for setup_retrieve_list_of_measuring_units

        Get the list of measuring units. 🔐  # noqa: E501
        """
        pass

    def test_setup_retrieve_list_of_states(self):
        """Test case for setup_retrieve_list_of_states

        Get the list of states/provinces. 🔐  # noqa: E501
        """
        pass

    def test_setup_retrieve_list_of_towns(self):
        """Test case for setup_retrieve_list_of_towns

        Get the list of towns. 🔐  # noqa: E501
        """
        pass

    def test_setup_retrieve_list_ofsocial_networks(self):
        """Test case for setup_retrieve_list_ofsocial_networks

        Get the list of social networks. 🔐  # noqa: E501
        """
        pass

    def test_setup_retrieve_modules(self):
        """Test case for setup_retrieve_modules

        Get list of enabled modules 🔐  # noqa: E501
        """
        pass

    def test_setup_retrieve_ordering_methods(self):
        """Test case for setup_retrieve_ordering_methods

        Get the list of ordering methods. 🔐  # noqa: E501
        """
        pass

    def test_setup_retrieve_ordering_origins(self):
        """Test case for setup_retrieve_ordering_origins

        Get the list of ordering origins. 🔐  # noqa: E501
        """
        pass

    def test_setup_retrieve_payment_terms(self):
        """Test case for setup_retrieve_payment_terms

        Get the list of payments terms. 🔐  # noqa: E501
        """
        pass

    def test_setup_retrieve_payment_types(self):
        """Test case for setup_retrieve_payment_types

        Get the list of payments types. 🔐  # noqa: E501
        """
        pass

    def test_setup_retrieve_shipping_modes(self):
        """Test case for setup_retrieve_shipping_modes

        Get the list of shipping methods. 🔐  # noqa: E501
        """
        pass

    def test_setup_retrieve_state_by_code(self):
        """Test case for setup_retrieve_state_by_code

        Get state by Code. 🔐  # noqa: E501
        """
        pass

    def test_setup_retrieve_state_by_id(self):
        """Test case for setup_retrieve_state_by_id

        Get state by ID. 🔐  # noqa: E501
        """
        pass

    def test_setup_retrieve_tickets_categories(self):
        """Test case for setup_retrieve_tickets_categories

        Get the list of tickets categories. 🔐  # noqa: E501
        """
        pass

    def test_setup_retrieve_tickets_severities(self):
        """Test case for setup_retrieve_tickets_severities

        Get the list of tickets severity. 🔐  # noqa: E501
        """
        pass

    def test_setup_retrieve_tickets_types(self):
        """Test case for setup_retrieve_tickets_types

        Get the list of tickets types. 🔐  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
