# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation  # noqa: E501

    OpenAPI spec version: 1
    Contact: arul@luracast.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.bankaccounts_transfer_model import BankaccountsTransferModel  # noqa: E501
from swagger_client.rest import ApiException


class TestBankaccountsTransferModel(unittest.TestCase):
    """BankaccountsTransferModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBankaccountsTransferModel(self):
        """Test BankaccountsTransferModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.bankaccounts_transfer_model.BankaccountsTransferModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
