# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation  # noqa: E501

    OpenAPI spec version: 1
    Contact: arul@luracast.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.proposals_api import ProposalsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProposalsApi(unittest.TestCase):
    """ProposalsApi unit test stubs"""

    def setUp(self):
        self.api = ProposalsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_proposals(self):
        """Test case for create_proposals

        Create commercial proposal object 🔐  # noqa: E501
        """
        pass

    def test_list_proposals(self):
        """Test case for list_proposals

        List commercial proposals 🔐  # noqa: E501
        """
        pass

    def test_proposals_close(self):
        """Test case for proposals_close

        Close (Accept or refuse) a quote / commercial proposal 🔐  # noqa: E501
        """
        pass

    def test_proposals_create_contact(self):
        """Test case for proposals_create_contact

        Add a contact type of given commercial proposal 🔐  # noqa: E501
        """
        pass

    def test_proposals_create_line(self):
        """Test case for proposals_create_line

        Add a line to given commercial proposal 🔐  # noqa: E501
        """
        pass

    def test_proposals_remove_contact(self):
        """Test case for proposals_remove_contact

        Delete a contact type of given commercial proposal 🔐  # noqa: E501
        """
        pass

    def test_proposals_remove_line(self):
        """Test case for proposals_remove_line

        Delete a line of given commercial proposal 🔐  # noqa: E501
        """
        pass

    def test_proposals_retrieve_by_ref(self):
        """Test case for proposals_retrieve_by_ref

        Get properties of an proposal object by ref 🔐  # noqa: E501
        """
        pass

    def test_proposals_retrieve_by_ref_ext(self):
        """Test case for proposals_retrieve_by_ref_ext

        Get properties of an proposal object by ref_ext 🔐  # noqa: E501
        """
        pass

    def test_proposals_retrieve_lines(self):
        """Test case for proposals_retrieve_lines

        Get lines of a commercial proposal 🔐  # noqa: E501
        """
        pass

    def test_proposals_setinvoiced(self):
        """Test case for proposals_setinvoiced

        Set a commercial proposal billed. Could be also called setbilled 🔐  # noqa: E501
        """
        pass

    def test_proposals_settodraft(self):
        """Test case for proposals_settodraft

        Set a proposal to draft 🔐  # noqa: E501
        """
        pass

    def test_proposals_update_line(self):
        """Test case for proposals_update_line

        Update a line of given commercial proposal 🔐  # noqa: E501
        """
        pass

    def test_proposals_validate(self):
        """Test case for proposals_validate

        Validate a commercial proposal 🔐  # noqa: E501
        """
        pass

    def test_remove_proposals(self):
        """Test case for remove_proposals

        Delete commercial proposal 🔐  # noqa: E501
        """
        pass

    def test_retrieve_proposals(self):
        """Test case for retrieve_proposals

        Get properties of a commercial proposal object 🔐  # noqa: E501
        """
        pass

    def test_update_proposals(self):
        """Test case for update_proposals

        Update commercial proposal general fields (won't touch lines of commercial proposal) 🔐  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
