# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation  # noqa: E501

    OpenAPI spec version: 1
    Contact: arul@luracast.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InvoicesUpdatePaymentModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'num_payment': 'str'
    }

    attribute_map = {
        'num_payment': 'num_payment'
    }

    def __init__(self, num_payment=None):  # noqa: E501
        """InvoicesUpdatePaymentModel - a model defined in Swagger"""  # noqa: E501
        self._num_payment = None
        self.discriminator = None
        if num_payment is not None:
            self.num_payment = num_payment

    @property
    def num_payment(self):
        """Gets the num_payment of this InvoicesUpdatePaymentModel.  # noqa: E501

        Payment number  # noqa: E501

        :return: The num_payment of this InvoicesUpdatePaymentModel.  # noqa: E501
        :rtype: str
        """
        return self._num_payment

    @num_payment.setter
    def num_payment(self, num_payment):
        """Sets the num_payment of this InvoicesUpdatePaymentModel.

        Payment number  # noqa: E501

        :param num_payment: The num_payment of this InvoicesUpdatePaymentModel.  # noqa: E501
        :type: str
        """

        self._num_payment = num_payment

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InvoicesUpdatePaymentModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InvoicesUpdatePaymentModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
