# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation  # noqa: E501

    OpenAPI spec version: 1
    Contact: arul@luracast.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProductsAddAttributesModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ref': 'str',
        'label': 'str',
        'ref_ext': 'str'
    }

    attribute_map = {
        'ref': 'ref',
        'label': 'label',
        'ref_ext': 'ref_ext'
    }

    def __init__(self, ref=None, label=None, ref_ext=None):  # noqa: E501
        """ProductsAddAttributesModel - a model defined in Swagger"""  # noqa: E501
        self._ref = None
        self._label = None
        self._ref_ext = None
        self.discriminator = None
        self.ref = ref
        self.label = label
        if ref_ext is not None:
            self.ref_ext = ref_ext

    @property
    def ref(self):
        """Gets the ref of this ProductsAddAttributesModel.  # noqa: E501

        Reference of Attribute  # noqa: E501

        :return: The ref of this ProductsAddAttributesModel.  # noqa: E501
        :rtype: str
        """
        return self._ref

    @ref.setter
    def ref(self, ref):
        """Sets the ref of this ProductsAddAttributesModel.

        Reference of Attribute  # noqa: E501

        :param ref: The ref of this ProductsAddAttributesModel.  # noqa: E501
        :type: str
        """
        if ref is None:
            raise ValueError("Invalid value for `ref`, must not be `None`")  # noqa: E501

        self._ref = ref

    @property
    def label(self):
        """Gets the label of this ProductsAddAttributesModel.  # noqa: E501

        Label of Attribute  # noqa: E501

        :return: The label of this ProductsAddAttributesModel.  # noqa: E501
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this ProductsAddAttributesModel.

        Label of Attribute  # noqa: E501

        :param label: The label of this ProductsAddAttributesModel.  # noqa: E501
        :type: str
        """
        if label is None:
            raise ValueError("Invalid value for `label`, must not be `None`")  # noqa: E501

        self._label = label

    @property
    def ref_ext(self):
        """Gets the ref_ext of this ProductsAddAttributesModel.  # noqa: E501

        Reference of Attribute  # noqa: E501

        :return: The ref_ext of this ProductsAddAttributesModel.  # noqa: E501
        :rtype: str
        """
        return self._ref_ext

    @ref_ext.setter
    def ref_ext(self, ref_ext):
        """Sets the ref_ext of this ProductsAddAttributesModel.

        Reference of Attribute  # noqa: E501

        :param ref_ext: The ref_ext of this ProductsAddAttributesModel.  # noqa: E501
        :type: str
        """

        self._ref_ext = ref_ext

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProductsAddAttributesModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProductsAddAttributesModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
