# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation  # noqa: E501

    OpenAPI spec version: 1
    Contact: arul@luracast.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ThirdpartiesSetThirdpartyPriceLevelModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'price_level': 'int'
    }

    attribute_map = {
        'price_level': 'priceLevel'
    }

    def __init__(self, price_level=None):  # noqa: E501
        """ThirdpartiesSetThirdpartyPriceLevelModel - a model defined in Swagger"""  # noqa: E501
        self._price_level = None
        self.discriminator = None
        self.price_level = price_level

    @property
    def price_level(self):
        """Gets the price_level of this ThirdpartiesSetThirdpartyPriceLevelModel.  # noqa: E501

        Price level to apply to thirdparty  # noqa: E501

        :return: The price_level of this ThirdpartiesSetThirdpartyPriceLevelModel.  # noqa: E501
        :rtype: int
        """
        return self._price_level

    @price_level.setter
    def price_level(self, price_level):
        """Sets the price_level of this ThirdpartiesSetThirdpartyPriceLevelModel.

        Price level to apply to thirdparty  # noqa: E501

        :param price_level: The price_level of this ThirdpartiesSetThirdpartyPriceLevelModel.  # noqa: E501
        :type: int
        """
        if price_level is None:
            raise ValueError("Invalid value for `price_level`, must not be `None`")  # noqa: E501

        self._price_level = price_level

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ThirdpartiesSetThirdpartyPriceLevelModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ThirdpartiesSetThirdpartyPriceLevelModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
